trigger:
- main

pool: Default

steps:
- task: Docker@2
  displayName: 'Build log4j vulnerable image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '-t vulnlog4j:latest'

- task: prisma-cloud-compute-scan@3
  inputs:
    scanType: 'images'
    twistlockService: 'PrismaCompute'
    artifact: ' vulnlog4j:latest'